#!/usr/bin/env python
"""28 haftalık ders akışından content/weeks/hafta-XX.md dosyalarını üretir.

Bu script yalnızca İLK iskeleti oluşturmak içindir. Var olan bir dosyanın üzerine
yazmaz (--force verilmedikçe); böylece elle düzenlenen ders notları korunur.

Kullanım:
  /opt/miniconda3/envs/ferhat_ml/bin/python scripts/generate_week_files.py [--force]
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "content" / "weeks"
MODULES = json.loads((ROOT / "content" / "data" / "modules.json").read_text(encoding="utf-8"))

def module_of(week):
    for m in MODULES:
        if week in m["weeks"]:
            return m
    raise KeyError(week)

# ---------------------------------------------------------------------------
# Haftalık içerik (DOCX'teki ders akışı esas alınmıştır; "topic" alanı özgün metindir)
# ---------------------------------------------------------------------------
WEEKS = [
 dict(n=1, title="Yapay Zekâ Tıbbı Nasıl Dönüştürüyor? İlk Kod",
  topic="Yapay zekânın tıbbı dönüştürmesi ve çalışma ortamının kurulumu (Google Colab/Jupyter); ilk kod",
  desc="Yapay zekânın tıptaki yerine genel bakış, Google Colab ortamının kurulumu ve ilk Python kodunuz.",
  tags=["yapay zekâ", "colab", "jupyter", "python", "giriş"],
  objectives=["Yapay zekânın tıpta kullanıldığı başlıca alanları (görüntüleme, karar destek, üretken YZ) sıralar.",
              "Google Colab / Jupyter ortamını açar, bir not defteri oluşturur ve hücre çalıştırır.",
              "İlk Python komutlarını (print, basit aritmetik) yazar ve çıktısını yorumlar."],
  concepts=[("Yapay zekâ (YZ)", "Normalde insan zekâsı gerektiren görevleri yerine getiren bilgisayar sistemleri; tıpta çoğunlukla veriden öğrenen modeller biçiminde karşımıza çıkar."),
            ("Not defteri (notebook)", "Kod, çıktı ve açıklama metnini aynı belgede tutan etkileşimli çalışma ortamı."),
            ("Hücre", "Not defterinde tek başına çalıştırılabilen kod veya metin bloğu.")],
  examples=["Göğüs röntgeninde pnömoni bulgularını işaretleyen bir model radyoloğun iş yükünü nasıl değiştirir?",
            "Bir hastane, sepsis riskini erken uyaran algoritmayı hangi verilerle besler?"],
  tools=["Google Colab", "Jupyter"],
  activity="Colab'de yeni bir not defteri açın; adınızı ve dersin adını yazdıran bir `print` komutu çalıştırın. Ardından iki vital bulguyu (nabız, sistolik basınç) değişkene atayıp toplamını yazdırın.",
  questions=["Hangi klinik kararlarda bir yazılımın öneri vermesini kabul edilebilir bulursunuz, hangilerinde bulmazsınız?",
             "“Kod yazabilen hekim” sizce ne anlama geliyor?"],
  summary="Bu hafta yapay zekânın tıptaki güncel rolünü tanıdık ve dersin çalışma ortamı olan Colab'de ilk kodumuzu yazdık.",
  before="Bir Google hesabınızın olduğundan emin olun; colab.research.google.com adresini tarayıcınızda açın."),

 dict(n=2, title="Python Temelleri I: Değişkenler ve Klinik Hesaplamalar",
  topic="Python temelleri I: değişkenler ve veri tipleri; basit klinik hesaplamalar (ör. VKİ)",
  desc="Değişkenler, sayı ve metin tipleri; vücut kitle indeksi gibi basit klinik hesaplamalar.",
  tags=["python", "değişken", "veri tipi", "VKİ", "BMI"],
  objectives=["Değişken tanımlar ve sayı, metin, mantıksal (bool) tiplerini ayırt eder.",
              "Aritmetik operatörlerle klinik bir formülü (VKİ) koda çevirir.",
              "Kullanıcıdan alınan girdiyi uygun tipe dönüştürür."],
  concepts=[("Değişken", "Bir değeri isimle saklayan kutu; `kilo = 72` gibi."),
            ("Veri tipi", "Değerin türü: tam sayı (int), ondalık (float), metin (str), mantıksal (bool)."),
            ("Tip dönüşümü", "`float(\"72.5\")` gibi bir metni sayıya çevirme işlemi.")],
  examples=["VKİ = kilo / boy² formülünü koda dökme ve DSÖ sınıflamasına göre yorumlama.",
            "Vücut yüzey alanı (Mosteller) hesabı ile kemoterapi dozu örneği."],
  tools=["Google Colab"],
  activity="Boy ve kiloyu değişkenlere atayıp VKİ hesaplayan bir hücre yazın; sonucu iki ondalıkla yazdırın.",
  questions=["Aynı formülü her hasta için elle hesaplamakla kodla hesaplamak arasında güvenlik açısından ne fark var?"],
  summary="Değişkenleri ve temel veri tiplerini öğrenip ilk klinik hesaplayıcımız olan VKİ'yi yazdık."),

 dict(n=3, title="Python Temelleri II: Listeler, Sözlükler ve Hasta Kayıtları",
  topic="Python temelleri II: listeler, sözlükler, döngüler ve koşullar; hasta kayıtlarıyla çalışma",
  desc="Liste ve sözlük yapıları, for döngüsü ve if koşulları ile hasta kayıtları üzerinde işlem.",
  tags=["python", "liste", "sözlük", "döngü", "koşul"],
  objectives=["Liste ve sözlük yapılarında veri saklar ve erişir.",
              "`for` döngüsüyle bir hasta listesini dolaşır.",
              "`if/elif/else` ile klinik eşiklere göre karar dallanması yazar."],
  concepts=[("Liste", "Sıralı değer topluluğu; `[120, 135, 98]` gibi bir sistolik basınç dizisi."),
            ("Sözlük", "Anahtar–değer çiftleri; `{\"ad\": \"A.Y.\", \"yas\": 54}` gibi bir hasta kaydı."),
            ("Döngü", "Aynı işlemi bir topluluğun her öğesi için tekrarlama."),
            ("Koşul", "Bir ifade doğruysa şu, değilse bu işlemi yapma.")],
  examples=["Bir hasta listesinde ateşi 38 °C üzerinde olanları işaretleme.",
            "Sözlük olarak tutulan hasta kaydından alerji bilgisini okuma."],
  tools=["Google Colab"],
  activity="Beş hastanın sistolik basınçlarını bir listeye koyun; döngüyle dolaşıp 140 üzerini “yüksek” olarak etiketleyin.",
  questions=["Gerçek hasta kayıtlarını böyle bir yapıda tutmanın sınırları neler olabilir?"],
  summary="Veri yapıları ve kontrol akışıyla artık birden fazla hasta üzerinde otomatik işlem yapabiliyoruz."),

 dict(n=4, title="Fonksiyonlar ve Okunabilir Kod: Klinik Hesaplayıcı",
  topic="Fonksiyonlar ve okunabilir kod; basit bir klinik hesaplayıcı geliştirme (ör. eGFR/risk skoru)",
  desc="Fonksiyon tanımlama, parametreler, okunabilir kod ilkeleri ve eGFR/risk skoru hesaplayıcısı.",
  tags=["python", "fonksiyon", "eGFR", "risk skoru", "temiz kod"],
  objectives=["`def` ile parametre alan ve değer döndüren fonksiyon yazar.",
              "Kodu anlamlı isimler ve açıklamalarla okunabilir hâle getirir.",
              "Bir klinik formülü (eGFR veya risk skoru) yeniden kullanılabilir fonksiyona dönüştürür."],
  concepts=[("Fonksiyon", "Bir işi yapan, isimlendirilmiş ve tekrar çağrılabilen kod bloğu."),
            ("Parametre / argüman", "Fonksiyona dışarıdan verilen girdiler."),
            ("Dönüş değeri", "Fonksiyonun `return` ile geri verdiği sonuç."),
            ("Okunabilirlik", "Kodun başka biri (ya da altı ay sonra siz) tarafından kolay anlaşılması.")],
  examples=["CKD-EPI eGFR formülünü fonksiyon olarak yazıp evre sınıflaması yapma.",
            "CHA₂DS₂-VASc skorunu hesaplayan fonksiyon."],
  tools=["Google Colab"],
  activity="Kreatinin, yaş ve cinsiyet alan bir `egfr()` fonksiyonu yazın; üç farklı hasta için çağırın ve evreyi yazdırın.",
  questions=["Bir klinik hesaplayıcıda yapılan küçük bir kod hatası nasıl sonuçlar doğurabilir? Bunu nasıl fark ederiz?"],
  summary="Fonksiyonlarla kodu parçalara ayırdık ve ilk gerçek klinik hesaplayıcımızı geliştirdik. Python temelleri modülü tamamlandı."),

 dict(n=5, title="NumPy ile Sayısal Hesaplama: Vital ve Laboratuvar Verileri",
  topic="NumPy ile sayısal hesaplama; vital ve laboratuvar verileri üzerinde vektör işlemleri",
  desc="NumPy dizileri, vektörel işlemler ve laboratuvar sonuçları üzerinde toplu hesaplama.",
  tags=["numpy", "dizi", "vektör", "laboratuvar"],
  objectives=["NumPy dizisi oluşturur ve döngü kullanmadan toplu işlem yapar.",
              "Ortalama, standart sapma, en küçük/en büyük gibi özet değerleri hesaplar.",
              "Mantıksal maskeleme ile eşik dışı değerleri seçer."],
  concepts=[("Dizi (array)", "Aynı tipte değerlerin hızlı işlenebilen topluluğu."),
            ("Vektörleştirme", "Döngü yazmadan tüm diziye aynı işlemi tek satırda uygulama."),
            ("Maskeleme", "`hb < 12` gibi bir koşulla dizinin alt kümesini seçme.")],
  examples=["100 hastanın hemoglobin değerlerinde anemi eşiği altındakileri sayma.",
            "24 saatlik nabız kayıtlarından ortalama ve değişkenlik hesabı."],
  tools=["NumPy", "Google Colab"],
  activity="Rastgele üretilmiş 200 açlık glukoz değeri üzerinde ortalama, standart sapma ve 126 mg/dL üzeri oranını hesaplayın.",
  questions=["Referans aralıkları popülasyona göre neden değişir; bu bir hesaplama koduna nasıl yansır?"],
  summary="NumPy ile binlerce ölçümü tek satırda işlemeyi öğrendik; bu, veri analizinin temel taşıdır."),

 dict(n=6, title="Pandas I: Sağlık Veri Setini Yükleme ve Keşfetme",
  topic="Pandas I: tablo verisini okuma, sağlık veri setini (CSV) yükleme ve keşfetme",
  desc="DataFrame kavramı, CSV okuma, sütun seçme, filtreleme ve veri setini tanıma.",
  tags=["pandas", "csv", "dataframe", "veri seti"],
  objectives=["Bir CSV dosyasını DataFrame olarak yükler.",
              "`head`, `info`, `describe` ile veri setini tanır.",
              "Sütun seçme ve satır filtreleme yapar."],
  concepts=[("DataFrame", "Satır ve sütunlardan oluşan, Excel tablosuna benzeyen veri yapısı."),
            ("CSV", "Virgülle ayrılmış düz metin veri dosyası; en yaygın paylaşım biçimi."),
            ("Filtreleme", "Belirli koşulu sağlayan satırları seçme.")],
  examples=["Açık bir diyabet veri setini yükleyip yaş ve HbA1c dağılımına bakma.",
            "Kalp hastalığı veri setinde göğüs ağrısı tipine göre hasta sayısı."],
  tools=["Pandas", "Google Colab"],
  activity="Kaggle'dan bir sağlık veri seti (ör. Pima diyabet) yükleyin; sütunları listeleyin, 50 yaş üstü hastaları filtreleyin.",
  questions=["Bir veri setine ilk baktığınızda hangi soruları sorarsınız? Verinin nereden geldiği neden önemlidir?"],
  summary="Gerçek bir sağlık veri setini ilk kez yükledik ve temel keşif adımlarını uyguladık."),

 dict(n=7, title="Pandas II: Veri Temizleme, Eksik Veri ve Özetleme",
  topic="Pandas II: veri temizleme, eksik veri yönetimi, gruplama ve özetleme",
  desc="Eksik değerlerin saptanması ve yönetimi, tip düzeltme, gruplayarak özetleme.",
  tags=["pandas", "eksik veri", "groupby", "veri temizleme"],
  objectives=["Eksik değerleri saptar; silme veya doldurma stratejilerini karşılaştırır.",
              "Hatalı tipleri ve aykırı kayıtları düzeltir.",
              "`groupby` ile alt gruplara göre özet istatistik üretir."],
  concepts=[("Eksik veri (NaN)", "Ölçülmemiş ya da kaydedilmemiş değer; klinik veride çok yaygındır."),
            ("İmputasyon", "Eksik değeri ortalama, medyan veya başka yöntemle doldurma."),
            ("Gruplama", "Veriyi kategoriye (cinsiyet, yaş grubu) göre bölüp her grupta özet hesaplama.")],
  examples=["Laboratuvar tablosunda eksik kreatinin değerlerinin oranını bulma.",
            "Cinsiyete göre ortalama sistolik basınç karşılaştırması."],
  tools=["Pandas"],
  activity="Veri setinizdeki eksik değerleri sütun başına sayın; bir sütunu medyanla doldurun ve yaş grubuna göre ortalama glukozu hesaplayın.",
  questions=["Eksik verinin rastgele olmaması (ör. ağır hastalarda daha çok ölçüm) sonuçları nasıl saptırır?"],
  summary="Gerçek dünyadaki dağınık veriyi analiz edilebilir hâle getirmenin yollarını öğrendik."),

 dict(n=8, title="Ara Değerlendirme ve Görselleştirme I: Epidemiyolojik Grafikler",
  topic="Ara değerlendirme ve veri görselleştirme I: Matplotlib/Seaborn ile epidemiyolojik grafikler",
  desc="Ara değerlendirme; Matplotlib ve Seaborn ile çubuk, çizgi ve histogram grafikler.",
  tags=["matplotlib", "seaborn", "grafik", "epidemiyoloji", "ara sınav"],
  exam=True,
  objectives=["Çubuk, çizgi ve histogram grafiklerini oluşturur.",
              "Eksen, başlık ve etiketlerle grafiği okunur kılar.",
              "Bir salgın eğrisini veya insidans zaman serisini çizer."],
  concepts=[("Histogram", "Sürekli bir değişkenin dağılımını gösteren grafik."),
            ("Zaman serisi", "Zamana göre sıralanmış ölçümler; salgın eğrisi bunun bir örneğidir."),
            ("Eksen ölçeği", "Doğrusal ya da logaritmik ölçek seçimi yorumu değiştirir.")],
  examples=["Haftalık vaka sayılarından salgın eğrisi çizme.",
            "Yaş gruplarına göre hipertansiyon prevalansı çubuk grafiği."],
  tools=["Matplotlib", "Seaborn"],
  activity="Veri setinizden yaş histogramı ve cinsiyete göre ortalama VKİ çubuk grafiği çizin; başlık ve eksen etiketlerini ekleyin.",
  questions=["Aynı veriyi farklı ölçeklerle çizmek izleyiciyi nasıl yanıltabilir?"],
  summary="İlk yarıyılın ara değerlendirmesini yaptık ve veriyi grafiğe dökmeye başladık.",
  before="Ara değerlendirme 1–7. haftaların içeriğini kapsar. Colab defterlerinizi gözden geçirin."),

 dict(n=9, title="Görselleştirme II: Dağılımlar, Korelasyon ve Veriyle Hikâye",
  topic="Veri görselleştirme II: dağılımlar, korelasyon ve veriyle görsel hikâye anlatımı",
  desc="Kutu grafiği, saçılım grafiği, korelasyon ısı haritası ve etkili görsel anlatım ilkeleri.",
  tags=["görselleştirme", "korelasyon", "saçılım", "kutu grafiği"],
  objectives=["Kutu ve saçılım grafikleriyle dağılım ve ilişkiyi gösterir.",
              "Korelasyon katsayısını hesaplar ve ısı haritasında okur.",
              "Bir bulguyu tek bir grafikle açık ve dürüst biçimde anlatır."],
  concepts=[("Kutu grafiği", "Medyan, çeyrekler ve aykırı değerleri özetleyen grafik."),
            ("Saçılım grafiği", "İki sayısal değişken arasındaki ilişkiyi noktalarla gösterir."),
            ("Korelasyon", "İki değişkenin birlikte değişme derecesi; nedensellik anlamına gelmez.")],
  examples=["VKİ ile açlık glukozu arasındaki ilişkiyi saçılım grafiğiyle inceleme.",
            "Laboratuvar parametreleri arasında korelasyon ısı haritası."],
  tools=["Matplotlib", "Seaborn", "Pandas"],
  activity="Veri setinizde iki değişken seçip saçılım grafiği çizin, korelasyonu hesaplayın ve bulgunuzu iki cümleyle yazın.",
  questions=["“Korelasyon nedensellik değildir” cümlesine klinik bir örnek verin."],
  summary="Değişkenler arasındaki ilişkileri görmeyi ve veriyle dürüst bir hikâye anlatmayı öğrendik."),

 dict(n=10, title="Tanımlayıcı İstatistik ve Olasılık Sezgisi",
  topic="Tanımlayıcı istatistik ve olasılık sezgisi; sağlık ölçümlerinin yorumlanması",
  desc="Merkezi eğilim, yayılım, normal dağılım ve olasılığın klinik ölçümlerde yorumu.",
  tags=["istatistik", "ortalama", "medyan", "standart sapma", "olasılık"],
  objectives=["Ortalama, medyan, mod ve standart sapmayı hesaplayıp uygun olanı seçer.",
              "Normal dağılım ve referans aralığı ilişkisini açıklar.",
              "Duyarlılık, özgüllük ve ön-test olasılığı arasındaki ilişkiyi sezgisel olarak kavrar."],
  concepts=[("Medyan", "Sıralı verinin ortasındaki değer; aykırı değerlerden etkilenmez."),
            ("Standart sapma", "Değerlerin ortalamadan ne kadar saçıldığının ölçüsü."),
            ("Referans aralığı", "Sağlıklı popülasyonun genellikle %95'ini kapsayan aralık."),
            ("Bayes sezgisi", "Testin sonucu, hastalığın ne kadar yaygın olduğuna göre farklı anlam taşır.")],
  examples=["Hastanede yatış süresi için ortalama mı medyan mı raporlanmalı?",
            "Nadir bir hastalık için pozitif test sonucunun gerçek pozitif olma olasılığı."],
  tools=["Pandas", "NumPy"],
  activity="Veri setinizdeki bir laboratuvar değişkeni için ortalama, medyan, SS hesaplayın; histogramla birlikte yorumlayın.",
  questions=["%99 doğru bir tarama testi, 10.000'de 1 görülen bir hastalıkta neden çok sayıda yanlış pozitif verir?"],
  summary="Sayıları özetlemeyi ve olasılık diliyle klinik ölçümleri yorumlamayı öğrendik."),

 dict(n=11, title="Çıkarımsal İstatistiğe Giriş: p-Değeri ve Güven Aralığı",
  topic="Çıkarımsal istatistiğe giriş: hipotez testi, p-değeri ve güven aralığı; yaygın yanlış yorumlar",
  desc="Hipotez testi mantığı, p-değeri, güven aralığı ve literatürde sık yapılan yanlış yorumlar.",
  tags=["istatistik", "p-değeri", "güven aralığı", "hipotez testi"],
  objectives=["Sıfır hipotezi ve alternatif hipotezi tanımlar.",
              "p-değerini doğru cümleyle ifade eder; yaygın yanılgıları ayırt eder.",
              "Güven aralığını klinik anlamlılıkla birlikte yorumlar."],
  concepts=[("p-değeri", "Sıfır hipotezi doğruyken gözlenen ya da daha uç bir sonucu görme olasılığı."),
            ("Güven aralığı", "Gerçek etkinin makul olarak bulunabileceği değer aralığı."),
            ("İstatistiksel vs klinik anlamlılık", "Küçük bir p-değeri, etkinin klinik olarak önemli olduğu anlamına gelmez.")],
  examples=["İki tedavi grubunun ortalama kan basıncını t-testi ile karşılaştırma.",
            "Büyük örneklemde istatistiksel olarak anlamlı ama klinik olarak önemsiz bir fark."],
  tools=["SciPy", "Pandas"],
  activity="Veri setinizde iki grubu (ör. sigara içen/içmeyen) karşılaştırın; t-testi uygulayın ve sonucu doğru bir cümleyle raporlayın.",
  questions=["“p = 0,06 olduğu için etki yoktur” cümlesi neden hatalıdır?"],
  summary="Bir farkın şansa bağlı olup olmadığını değerlendirmenin temel araçlarını ve tuzaklarını gördük."),

 dict(n=12, title="Makine Öğrenmesine Giriş I: Denetimli Öğrenme ve İlk Model",
  topic="Makine öğrenmesine giriş I: denetimli öğrenme, eğitim/test ayrımı, basit sınıflandırma",
  desc="Denetimli öğrenme kavramı, eğitim/test ayrımı ve scikit-learn ile ilk sınıflandırma modeli.",
  tags=["makine öğrenmesi", "scikit-learn", "sınıflandırma", "eğitim/test"],
  objectives=["Denetimli öğrenmeyi ve etiketli veri kavramını açıklar.",
              "Veriyi eğitim ve test kümelerine ayırmanın nedenini kavrar.",
              "scikit-learn ile lojistik regresyon veya karar ağacı modeli eğitir."],
  concepts=[("Denetimli öğrenme", "Girdi ve doğru cevap (etiket) çiftlerinden öğrenen yöntem."),
            ("Özellik (feature)", "Modelin kullandığı girdi değişkeni; yaş, HbA1c gibi."),
            ("Eğitim / test ayrımı", "Modelin görmediği veride sınanması; ezberlemeyi ortaya çıkarır."),
            ("Aşırı öğrenme (overfitting)", "Modelin eğitim verisini ezberleyip yeni veride başarısız olması.")],
  examples=["Yaş, VKİ ve glukoz ile diyabet tanısı öngören basit model.",
            "Klinik verilerden kalp hastalığı varlığını sınıflandırma."],
  tools=["scikit-learn", "Pandas"],
  activity="Diyabet veri setini eğitim/test olarak bölün; lojistik regresyon eğitin ve test doğruluğunu hesaplayın.",
  questions=["Model eğitim verisinde %99 doğru ama test verisinde %70 ise ne olmuştur?"],
  summary="Bilgisayarın veriden nasıl “öğrendiğini” gördük ve ilk tahmin modelimizi kurduk."),

 dict(n=13, title="Makine Öğrenmesine Giriş II: Model Değerlendirme ve ROC",
  topic="Makine öğrenmesine giriş II: model değerlendirme (duyarlılık/özgüllük, ROC) ve tıpta önemi",
  desc="Karışıklık matrisi, duyarlılık, özgüllük, PPV/NPV, ROC eğrisi ve eşik seçimi.",
  tags=["ROC", "duyarlılık", "özgüllük", "karışıklık matrisi", "AUC"],
  objectives=["Karışıklık matrisinden duyarlılık, özgüllük, PPV ve NPV hesaplar.",
              "ROC eğrisini çizer ve AUC'yi yorumlar.",
              "Klinik bağlama göre karar eşiğini tartışır."],
  concepts=[("Karışıklık matrisi", "Doğru/yanlış pozitif ve negatif sayılarının tablosu."),
            ("Duyarlılık / özgüllük", "Hastaları yakalama ve sağlıklıları doğru ayırma oranları."),
            ("ROC eğrisi ve AUC", "Tüm eşiklerde duyarlılık–özgüllük dengesini gösteren eğri ve altındaki alan."),
            ("Eşik", "Modelin “pozitif” demeye başladığı olasılık sınırı; klinik maliyete göre seçilir.")],
  examples=["Tarama testinde duyarlılığı yüksek tutmanın yanlış pozitif maliyeti.",
            "Sepsis uyarı modelinde eşik düşürülünce alarm yorgunluğu."],
  tools=["scikit-learn", "Matplotlib"],
  activity="Geçen haftaki modelin ROC eğrisini çizin; AUC hesaplayın ve iki farklı eşikte duyarlılık/özgüllüğü karşılaştırın.",
  questions=["Doğruluk (accuracy) tıpta neden çoğu zaman yanıltıcı bir ölçüttür?"],
  summary="Bir modelin klinik açıdan iyi olup olmadığını değerlendirmenin doğru ölçütlerini öğrendik."),

 dict(n=14, title="Mini Proje Atölyesi: Uçtan Uca Sağlık Verisi Analizi",
  topic="Mini proje atölyesi ve genel değerlendirme: uçtan uca bir sağlık-veri analizi",
  desc="Yarıyılın tüm adımlarını birleştiren mini proje: veri yükleme, temizleme, görselleştirme, model ve rapor.",
  tags=["proje", "atölye", "veri analizi", "değerlendirme"],
  objectives=["Bir sağlık veri setinde yükleme–temizleme–görselleştirme–modelleme akışını uçtan uca uygular.",
              "Bulgularını kısa bir raporda açık ve dürüst biçimde sunar.",
              "Yarıyıl boyunca öğrenilenleri gözden geçirir."],
  concepts=[("Analiz akışı (pipeline)", "Ham veriden sonuca giden tekrarlanabilir adımlar zinciri."),
            ("Tekrarlanabilirlik", "Aynı kod ve veriyle aynı sonuca ulaşılabilmesi.")],
  examples=["Seçilen açık veri setinde bir klinik soruyu baştan sona yanıtlama."],
  tools=["Pandas", "Matplotlib", "scikit-learn", "Google Colab"],
  activity="Gruplar hâlinde bir veri seti seçin; klinik bir soru belirleyin ve analiz akışını tek bir Colab defterinde tamamlayın.",
  questions=["Analizinizin sınırlılıkları neler? Sonuçlarınızı bir kliniğe uygulamak için ne gerekir?"],
  summary="Güz yarıyılını, öğrendiğimiz tüm araçları birleştiren bir mini projeyle tamamladık.",
  before="Modül 1–4 defterlerinizi ve veri setinizi hazır bulundurun."),

 dict(n=15, title="Tıbbi Görüntülerde Derin Öğrenme Sezgisi",
  topic="Tıbbi görüntülerde derin öğrenme sezgisi (röntgen/patoloji); hazır modellerle uygulama",
  desc="Yapay sinir ağları ve evrişimli ağların (CNN) sezgisel açıklaması; hazır modellerle röntgen/patoloji uygulaması.",
  tags=["derin öğrenme", "CNN", "tıbbi görüntüleme", "röntgen", "patoloji"],
  objectives=["Yapay sinir ağının ve evrişimli ağın (CNN) ne yaptığını matematiğe girmeden açıklar.",
              "Hazır bir görüntü modelini çalıştırıp çıktısını yorumlar.",
              "Görüntü modellerinin başarısızlık biçimlerini (veri kayması, kısayol öğrenme) tanır."],
  concepts=[("Yapay sinir ağı", "Katmanlar hâlinde dizilmiş basit hesap birimlerinden oluşan model."),
            ("Evrişimli sinir ağı (CNN)", "Görüntüdeki kenar, doku ve şekil gibi örüntüleri katman katman öğrenen ağ."),
            ("Kısayol öğrenme", "Modelin hastalığı değil, görüntüdeki ilgisiz bir ipucunu (cihaz etiketi) öğrenmesi."),
            ("Isı haritası (Grad-CAM)", "Modelin karar verirken görüntünün nereye baktığını gösteren görselleştirme.")],
  examples=["Göğüs röntgeninde pnömoni sınıflandırması yapan açık bir model.",
            "Patoloji lamında tümör alanlarını işaretleme; dermatolojide melanom sınıflandırması."],
  tools=["Google Colab", "Hazır (önceden eğitilmiş) modeller"],
  activity="Verilen not defterinde hazır bir röntgen modelini birkaç görüntü üzerinde çalıştırın; ısı haritasını inceleyip modelin nereye baktığını tartışın.",
  questions=["Bir görüntü modeli radyoloğun yerini alabilir mi, yoksa nasıl bir iş bölümü daha gerçekçidir?"],
  summary="Görüntü tanıyan modellerin çalışma mantığını ve sınırlarını sezgisel düzeyde kavradık."),

 dict(n=16, title="Sağlıkta Tahmin ve Karar Destek: Yanlılık ve Eşitlik",
  topic="Sağlıkta tahmin ve karar destek modelleri; model çıktısını klinik karara çevirme, yanlılık/eşitlik",
  desc="Klinik karar destek sistemleri, model çıktısının karara dönüşümü, algoritmik yanlılık ve eşitlik.",
  tags=["karar destek", "yanlılık", "eşitlik", "tahmin modeli", "CDSS"],
  objectives=["Klinik karar destek sisteminin bileşenlerini ve iş akışına yerleşimini açıklar.",
              "Bir olasılık çıktısının klinik karara nasıl çevrildiğini örnekler.",
              "Algoritmik yanlılığın kaynaklarını ve etkilenen grupları tanımlar."],
  concepts=[("Klinik karar destek (CDSS)", "Hekime karar anında veri temelli öneri sunan sistem."),
            ("Kalibrasyon", "Modelin %30 dediği hastaların gerçekten yaklaşık %30'unun hasta olması."),
            ("Algoritmik yanlılık", "Modelin belirli gruplarda sistematik olarak daha kötü çalışması."),
            ("İnsan denetimi", "Nihai kararın ve sorumluluğun hekimde kalması ilkesi.")],
  examples=["Sepsis erken uyarı skorlarının gerçek hastanelerdeki performansı.",
            "Deri renginden etkilenen pulse oksimetre ölçümleri ve model yanlılığı; sağlık harcamasını hastalık şiddeti yerine kullanan algoritma örneği."],
  tools=["scikit-learn", "Pandas"],
  activity="Güz modelinizin performansını cinsiyet veya yaş gruplarına göre ayrı ayrı hesaplayın; fark varsa nedenlerini tartışın.",
  questions=["Bir model ortalamada iyi ama belirli bir grupta kötü çalışıyorsa kullanıma alınmalı mı?"],
  summary="Model çıktılarının klinik karara dönüşümünü ve bu süreçteki eşitlik sorunlarını inceledik."),

 dict(n=17, title="Büyük Dil Modelleri (LLM): Nasıl Çalışır, Neden Halüsinasyon Görür?",
  topic="Büyük dil modelleri (LLM) nedir, nasıl çalışır; tıpta olanaklar, sınırlar ve halüsinasyon",
  desc="LLM'lerin çalışma ilkesi, token ve olasılıksal üretim, tıptaki olanaklar, sınırlar ve halüsinasyon.",
  tags=["LLM", "büyük dil modeli", "halüsinasyon", "ChatGPT", "üretken yapay zekâ"],
  objectives=["LLM'nin bir sonraki kelimeyi tahmin eden olasılıksal bir model olduğunu açıklar.",
              "Halüsinasyonun neden kaçınılmaz bir özellik olduğunu kavrar.",
              "Tıpta LLM'lerin uygun ve uygunsuz kullanım alanlarını ayırt eder."],
  concepts=[("Büyük dil modeli (LLM)", "Devasa metin verisinden dil örüntülerini öğrenen, metin üreten model."),
            ("Token", "Modelin işlediği metin parçası; kelime veya kelime parçası."),
            ("Halüsinasyon", "Modelin akıcı ama gerçek dışı bilgi üretmesi."),
            ("Bilgi kesim tarihi", "Modelin eğitim verisinin bittiği tarih; sonrasını bilmez.")],
  examples=["Taburcu özetini hasta diline çevirme: faydalı ama denetim gerektirir.",
            "Uydurma ilaç dozu veya var olmayan kılavuz önerisi örnekleri."],
  tools=["ChatGPT", "Claude", "Gemini"],
  activity="Aynı klinik soruyu iki farklı LLM'ye sorun; yanıtları güvenilir bir kaynakla karşılaştırıp farkları not edin.",
  questions=["LLM'nin “emin” bir tonla yanlış bilgi vermesi hekim için neden özellikle tehlikelidir?"],
  summary="Sohbet botlarının arkasındaki mekanizmayı anladık ve çıktılarına neden şüpheyle yaklaşmamız gerektiğini gördük."),

 dict(n=18, title="Üretken Yapay Zekâ Okuryazarlığı: Araçların Etkin ve Eleştirel Kullanımı",
  topic="Üretken yapay zekâ okuryazarlığı: araçların (ChatGPT, Claude vb.) etkin ve eleştirel kullanımı",
  desc="Popüler üretken YZ araçlarının karşılaştırılması, güçlü ve zayıf yönleri, eleştirel kullanım ilkeleri.",
  tags=["üretken yapay zekâ", "ChatGPT", "Claude", "Gemini", "okuryazarlık"],
  objectives=["Başlıca üretken YZ araçlarını özellikleri ile karşılaştırır.",
              "Bir çıktının doğruluğunu kontrol etme alışkanlığı geliştirir.",
              "Araçların hangi görevlerde güvenilir yardımcı olduğunu belirler."],
  concepts=[("Üretken yapay zekâ", "Metin, görsel, ses gibi yeni içerik üreten YZ sistemleri."),
            ("Bağlam penceresi", "Modelin aynı anda dikkate alabildiği metin miktarı."),
            ("Web araması / kaynaklı yanıt", "Modelin güncel kaynaklara erişerek yanıt üretmesi."),
            ("Doğrulama refleksi", "Her önemli bilgiyi bağımsız kaynakla teyit etme alışkanlığı.")],
  examples=["Ders notlarını özetletme ve kendinize soru ürettirme.",
            "Bir makalenin yöntem bölümünü sade Türkçeyle açıklatma."],
  tools=["ChatGPT", "Claude", "Gemini", "NotebookLM"],
  activity="Bir ders konusunu üç farklı araçla özetletin; hangisinin daha doğru ve yararlı olduğunu ölçütlerle değerlendirin.",
  questions=["Hangi görevleri asla tek başına bir YZ aracına bırakmazsınız?"],
  summary="Üretken YZ araçlarını tanıdık ve eleştirel kullanımın temel alışkanlıklarını edindik."),

 dict(n=19, title="Prompt Mühendisliği I: Sistematik İstem Teknikleri",
  topic="Prompt mühendisliği I: akademik ve klinik görevler için sistematik istem (prompt) teknikleri",
  desc="Rol, bağlam, görev ve format bileşenleriyle etkili istem yazma; akademik ve klinik örnekler.",
  tags=["prompt", "istem mühendisliği", "prompt engineering"],
  objectives=["Etkili bir istemin bileşenlerini (rol, bağlam, görev, kısıt, format) sıralar.",
              "Belirsiz bir istemi adım adım iyileştirir.",
              "Örnek verme (few-shot) ve adım adım düşünme tekniklerini uygular."],
  concepts=[("İstem (prompt)", "Modele verilen yönerge ve bağlam metni."),
            ("Rol atama", "Modele “tıp eğitimcisi gibi yanıtla” gibi bir bakış açısı vermek."),
            ("Few-shot", "İstenen çıktının birkaç örneğini isteme eklemek."),
            ("Adım adım düşünme", "Modelden yanıta ulaşırken gerekçelerini açıkça yazmasını istemek.")],
  examples=["Bir farmakoloji konusunu sınav sorusuna dönüştüren istem.",
            "Vaka özeti için ayırıcı tanı listesi isteyen yapılandırılmış istem."],
  tools=["ChatGPT", "Claude"],
  activity="Kötü yazılmış bir istemi alın; her adımda tek bir bileşen ekleyerek beş sürüm üretin ve çıktı kalitesini karşılaştırın.",
  questions=["İyi bir istem yazmak, iyi bir anamnez almakla hangi açılardan benzer?"],
  summary="İstem yazmanın rastgele bir deneme değil, öğrenilebilir bir teknik olduğunu gördük."),

 dict(n=20, title="Prompt Mühendisliği II: Yapılandırılmış Çıktı ve Doğrulama",
  topic="Prompt mühendisliği II: yapılandırılmış çıktı, özetleme, vaka tartışması ve çıktının doğrulanması",
  desc="Tablo/JSON gibi yapılandırılmış çıktı isteme, uzun metin özetleme, vaka tartışması ve çıktı doğrulama.",
  tags=["prompt", "yapılandırılmış çıktı", "özetleme", "doğrulama"],
  objectives=["Modelden tablo veya JSON biçiminde yapılandırılmış çıktı alır.",
              "Uzun bir metni kayıpsız özetlemek için istem tasarlar.",
              "Model çıktısını kontrol listesiyle doğrular."],
  concepts=[("Yapılandırılmış çıktı", "Belirli bir şemaya uyan (tablo, JSON) çıktı; sonraki işlemleri kolaylaştırır."),
            ("Özetleme kaybı", "Özetlerde nüansların ve olumsuz bulguların düşme riski."),
            ("Öz-denetim istemi", "Modelden kendi yanıtını eleştirmesini isteme; hataları azaltabilir ama garanti etmez.")],
  examples=["Bir vaka metninden ilaç listesi ve dozları tablo hâlinde çıkarma.",
            "Kılavuz özetinin orijinalle satır satır karşılaştırılması."],
  tools=["ChatGPT", "Claude"],
  activity="Anonim bir vaka metnini tabloya dönüştüren istem yazın; çıktıyı orijinal metinle karşılaştırıp hataları listeleyin.",
  questions=["Bir YZ özetine güvenmek için hangi kontrol adımlarını asgari kabul edersiniz?"],
  summary="Model çıktısını işlenebilir yapıya sokmayı ve sistematik olarak doğrulamayı öğrendik."),

 dict(n=21, title="Yapay Zekâ ile Literatür Taraması ve Kanıta Dayalı Tıp",
  topic="Yapay zekâ ile literatür taraması ve kanıta dayalı tıp; uydurma referans (halüsinasyon) tuzakları",
  desc="YZ destekli literatür araçları, kanıta dayalı tıp piramidi, uydurma referans tuzağı ve doğrulama yolları.",
  tags=["literatür", "kanıta dayalı tıp", "referans", "halüsinasyon", "PubMed"],
  objectives=["YZ destekli literatür araçlarını (kaynaklı arama, özetleme) tanır.",
              "Kanıt düzeyleri hiyerarşisini YZ çıktısına uygular.",
              "Uydurma referansları saptamak için DOI/PubMed doğrulaması yapar."],
  concepts=[("Kanıta dayalı tıp", "Klinik kararın en iyi kanıt, hekim deneyimi ve hasta değerleriyle verilmesi."),
            ("Uydurma referans", "Modelin gerçek görünümlü ama var olmayan makale üretmesi."),
            ("DOI", "Bir yayının kalıcı dijital kimliği; doğrulamanın ilk adımı."),
            ("Kaynaklı üretim (RAG)", "Modelin yanıtı gerçek belgelerden alıntılarla üretmesi.")],
  examples=["Bir klinik soru için PICO oluşturup YZ ile arama stratejisi geliştirme.",
            "Modelin verdiği 5 referanstan kaçının gerçek olduğunu kontrol etme."],
  tools=["PubMed", "Semantic Scholar", "Elicit / Consensus", "ChatGPT", "Claude"],
  activity="Bir klinik soru için LLM'den 5 kaynak isteyin; her birini PubMed'de arayıp gerçek olup olmadığını tablolayın.",
  questions=["YZ araçları sistematik derlemede hangi adımları hızlandırır, hangilerinde risk yaratır?"],
  summary="YZ'yi literatürde bir hızlandırıcı olarak kullanmayı, ancak her kaynağı doğrulamayı öğrendik."),

 dict(n=22, title="Ara Değerlendirme ve Agentic Yapay Zekâ I: Ajan Kavramı",
  topic="Ara değerlendirme; agentic (ajan tabanlı) yapay zekâ I: ajan kavramı ve araç kullanımı",
  desc="Bahar ara değerlendirmesi; ajan (agent) kavramı, araç kullanımı ve çok adımlı görevler.",
  tags=["agentic", "ajan", "araç kullanımı", "ara sınav"],
  exam=True,
  objectives=["Ajan tabanlı YZ'yi sohbet botundan ayıran özellikleri (planlama, araç kullanma, döngü) açıklar.",
              "Bir ajanın hangi araçlara erişebileceğini ve bunun risklerini tartışır.",
              "Basit bir çok adımlı görevi ajana tanımlar."],
  concepts=[("Ajan (agent)", "Hedef doğrultusunda plan yapan, araç çağıran ve sonucu değerlendirip devam eden YZ sistemi."),
            ("Araç kullanımı", "Modelin hesap makinesi, web araması, kod çalıştırma gibi dış işlevleri çağırması."),
            ("Otonomi düzeyi", "İnsanın onayı olmadan ajanın ne kadar ileri gidebildiği.")],
  examples=["Bir veri setini indirip özetleyen ve grafik çizen ajan.",
            "Randevu ve hatırlatma akışlarını yürüten yardımcı sistemler."],
  tools=["ChatGPT (ileri veri analizi)", "Claude", "Colab"],
  activity="Bir ajan aracına “şu CSV dosyasını yükle, eksik verileri say ve yaş dağılımını çiz” görevini verin; adımlarını izleyin.",
  questions=["Ajanın hata yaptığında sorumluluk kimdedir?"],
  summary="Bahar ara değerlendirmesini yaptık ve kendi başına adım atabilen YZ sistemlerini tanımaya başladık.",
  before="Ara değerlendirme 15–21. haftaların içeriğini kapsar."),

 dict(n=23, title="Agentic Yapay Zekâ II: YZ'ye Kod ve Veri Analizi Yaptırma",
  topic="Agentic yapay zekâ II: yapay zekâya kod ve veri analizi yaptırma; çıktının doğrulanması ve sorumluluk",
  desc="YZ ile kod yazdırma ve veri analizi, üretilen kodun okunması ve doğrulanması, sorumluluk.",
  tags=["agentic", "kod üretimi", "veri analizi", "doğrulama", "sorumluluk"],
  objectives=["Bir analiz görevini YZ ajanına tanımlar ve üretilen kodu okur.",
              "Çıktıyı bağımsız hesaplamayla doğrular.",
              "Otomatik üretilen analizde sorumluluk ve şeffaflık ilkelerini uygular."],
  concepts=[("Kod üretimi", "Doğal dil talimatından çalışan kod yazılması."),
            ("Doğrulama", "Üretilen sonucu ikinci bir yolla (elle hesap, farklı kütüphane) kontrol etme."),
            ("Kara kutu riski", "Anlamadığınız kodun sonucuna güvenmenin tehlikesi.")],
  examples=["Güz mini projesinin aynı sorusunu YZ'ye çözdürüp kendi sonucunuzla karşılaştırma.",
            "Yanlış varsayımla (eksik verileri sıfır sayma) üretilen analiz örneği."],
  tools=["Claude", "ChatGPT", "Colab"],
  activity="Güz projenizdeki bir analizi YZ'ye yaptırın; ürettiği kodu satır satır açıklayın ve sonucu kendi sonucunuzla karşılaştırın.",
  questions=["Kendiniz yazamayacağınız bir kodu YZ'den alıp kullanmak etik midir? Hangi koşullarda?"],
  summary="YZ'ye analiz yaptırmanın gücünü ve bunun beraberinde getirdiği doğrulama sorumluluğunu deneyimledik."),

 dict(n=24, title="Yapay Zekâ Araçları Ekosistemi: Hekimlik İçin Faydalı Araçlar",
  topic="Yapay zekâ araçları ekosistemi: transkripsiyon, görsel/ses, NotebookLM ve hekimlik için faydalı araçlar",
  desc="Transkripsiyon, görsel ve ses üretimi, NotebookLM gibi araçlar ve hekimlik pratiğine uygun kullanım alanları.",
  tags=["araçlar", "transkripsiyon", "NotebookLM", "ses", "görsel"],
  objectives=["Konuşmayı metne çeviren araçları ve klinik not alma senaryolarını değerlendirir.",
              "NotebookLM gibi kaynak tabanlı çalışma araçlarını ders çalışmada kullanır.",
              "Görsel/ses üretim araçlarının eğitim materyali üretimindeki yerini tartışır."],
  concepts=[("Transkripsiyon", "Konuşmanın otomatik olarak yazıya dökülmesi."),
            ("Ortam dinleyen yazıcı (ambient scribe)", "Hasta görüşmesini dinleyip taslak not üreten sistem."),
            ("Kaynak tabanlı asistan", "Yalnızca sizin yüklediğiniz belgelerden yanıt üreten araç.")],
  examples=["Ders kaydını transkribe edip özet çıkarma.",
            "Anatomi çalışması için görsel üretim ve doğruluk sorunları."],
  tools=["Whisper", "NotebookLM", "Görsel üretim araçları"],
  activity="Kendi ders notlarınızı NotebookLM'e yükleyin; kaynaklı özet ve soru seti oluşturup doğruluğunu kontrol edin.",
  questions=["Hasta görüşmesini kaydeden bir araç kullanmanın önkoşulları neler olmalıdır?"],
  summary="Sohbet botlarının ötesindeki YZ araçlarını ve bunların hekimlikteki yerini gördük."),

 dict(n=25, title="Sağlık Verisinde Mahremiyet, KVKK ve Veri Güvenliği",
  topic="Sağlık verisinde mahremiyet, KVKK ve veri güvenliği; hasta verisinin yapay zekâ araçlarıyla kullanımı",
  desc="Kişisel sağlık verisi kavramı, KVKK ilkeleri, anonimleştirme ve hasta verisinin YZ araçlarında kullanım kuralları.",
  tags=["KVKK", "mahremiyet", "veri güvenliği", "anonimleştirme", "hasta verisi"],
  objectives=["Sağlık verisinin “özel nitelikli kişisel veri” statüsünü ve sonuçlarını açıklar.",
              "Anonimleştirme ile takma adlandırma arasındaki farkı ayırt eder.",
              "Hasta verisini bir YZ aracına girmeden önce uygulanacak kontrol listesini kullanır."],
  concepts=[("Özel nitelikli kişisel veri", "Sağlık verisi dâhil, işlenmesi daha sıkı kurallara bağlı veri sınıfı."),
            ("Anonimleştirme", "Verinin hiçbir şekilde kişiyle eşleştirilemez hâle getirilmesi."),
            ("Takma adlandırma", "Kimliğin ayrı bir anahtarla saklanması; geri dönüş mümkündür."),
            ("Veri ihlali", "Yetkisiz erişim, sızıntı veya kayıp; bildirim yükümlülüğü doğurur.")],
  examples=["Bir vaka sorusunu sohbet botuna yazmadan önce hangi bilgiler çıkarılmalı?",
            "Ekran görüntüsündeki hasta etiketi ile yaşanan gerçek ihlal örnekleri."],
  tools=["KVKK rehberleri", "Kurumsal politika belgeleri"],
  activity="Verilen bir vaka metnini KVKK'ya uygun şekilde anonimleştirin; grubunuzla neyin kimlik belirleyici olduğunu tartışın.",
  questions=["Tamamen anonim veri mümkün müdür? Birkaç bilginin birleşmesi kimliği nasıl ortaya çıkarır?"],
  summary="Hasta verisini korumanın hukuki ve teknik temellerini ve YZ araçlarıyla güvenli çalışma kurallarını öğrendik."),

 dict(n=26, title="Tıpta Yapay Zekâ Etiği ve Regülasyon",
  topic="Tıpta yapay zekâ etiği ve regülasyon: sorumluluk, aydınlatılmış onam, şeffaflık, FDA/CE ve insan denetimi",
  desc="Etik ilkeler, sorumluluk, aydınlatılmış onam, şeffaflık ve açıklanabilirlik; FDA/CE onayı ve insan denetimi.",
  tags=["etik", "regülasyon", "FDA", "CE", "aydınlatılmış onam", "şeffaflık"],
  objectives=["Tıpta YZ için temel etik ilkeleri (yarar, zarar vermeme, adalet, özerklik) YZ bağlamında uygular.",
              "YZ destekli bir kararda sorumluluğun nasıl paylaşıldığını tartışır.",
              "FDA/CE gibi onay süreçlerinin neyi garanti edip etmediğini açıklar."],
  concepts=[("Açıklanabilirlik", "Modelin kararının insan tarafından anlaşılabilir gerekçeye bağlanabilmesi."),
            ("Aydınlatılmış onam", "Hastanın, kararda YZ kullanıldığını bilmesi ve kabul etmesi."),
            ("Tıbbi cihaz olarak yazılım (SaMD)", "Tanı/tedavi amaçlı yazılımların cihaz gibi düzenlenmesi."),
            ("İnsan denetimi (human-in-the-loop)", "Kritik kararlarda son sözün insanda kalması.")],
  examples=["FDA onaylı YZ ürünlerinin çoğunun radyolojide olması ve onayın anlamı.",
            "Model hata yaptığında hekim, kurum ve üretici arasındaki sorumluluk tartışması."],
  tools=["WHO etik rehberi", "FDA / CE kaynakları"],
  activity="Gruplar bir YZ ürününü seçip etik ilke kontrol listesiyle değerlendirir; sonucu sınıfa sunar.",
  questions=["Hastaya “bu öneriyi bir algoritma üretti” demek zorunlu olmalı mı?"],
  summary="YZ'nin klinikte güvenilir biçimde kullanımı için gereken etik ve düzenleyici çerçeveyi inceledik."),

 dict(n=27, title="Öğrenme Sürecinde Yapay Zekâ: Etik ve Etkin Kullanım, Akademik Dürüstlük",
  topic="Öğrenme sürecinde yapay zekânın etik ve etkin kullanımı; akademik dürüstlük",
  desc="YZ ile ders çalışmanın etkili yolları, öğrenmeyi engelleyen kullanım biçimleri ve akademik dürüstlük kuralları.",
  tags=["akademik dürüstlük", "öğrenme", "çalışma yöntemi", "intihal"],
  objectives=["YZ'nin öğrenmeyi derinleştiren ve sığlaştıran kullanımlarını ayırt eder.",
              "Akademik çalışmalarda YZ kullanımını uygun biçimde beyan eder.",
              "Kendisi için sürdürülebilir bir YZ destekli çalışma rutini tasarlar."],
  concepts=[("Bilişsel yük boşaltma", "Düşünme işini araca bırakmanın öğrenmeyi zayıflatması."),
            ("Sokratik kullanım", "YZ'den cevap yerine soru ve ipucu isteme."),
            ("Beyan (disclosure)", "Hangi işte YZ'nin nasıl kullanıldığının açıkça yazılması.")],
  examples=["Bir sınava hazırlanırken YZ'yi soru üreticisi ve geri bildirimci olarak kullanma.",
            "Ödevi tamamen YZ'ye yazdırmanın öğrenme ve dürüstlük açısından sonuçları."],
  tools=["ChatGPT", "Claude", "NotebookLM"],
  activity="Bir haftalık kişisel çalışma planı yazın; her adımda YZ'yi nasıl kullanacağınızı ve nerede kullanmayacağınızı belirtin.",
  questions=["Fakültenizin YZ kullanım politikası nasıl olmalı? Bir madde önerin."],
  summary="YZ'yi öğrenmenin yerine değil, hizmetine koymanın yollarını ve dürüstlük ilkelerini konuştuk."),

 dict(n=28, title="Proje Sunumları ve Geleceğe Bakış",
  topic="Proje sunumları, geleceğe bakış (hekimlikte YZ kariyer/araştırma yolları) ve genel değerlendirme",
  desc="Öğrenci proje sunumları, hekimlikte yapay zekâ kariyer ve araştırma yolları, yıl sonu değerlendirmesi.",
  tags=["proje", "sunum", "kariyer", "araştırma", "gelecek"],
  objectives=["Yıl boyunca geliştirilen projeyi açık ve eleştirel biçimde sunar.",
              "Hekimlikte YZ ile ilgili kariyer ve araştırma yollarını tanır.",
              "Kendi YZ okuryazarlığını değerlendirir ve sonraki öğrenme hedeflerini belirler."],
  concepts=[("Klinik veri bilimci hekim", "Klinik bilgiyle veri bilimini birleştiren yeni yetkinlik profili."),
            ("Translasyonel araştırma", "Model geliştirmeden klinik uygulamaya köprü kuran çalışma alanı.")],
  examples=["Tıbbi bilişim, klinik araştırma, sağlık teknolojileri girişimleri ve akademik yollar."],
  tools=["Sunum araçları", "Colab"],
  activity="Gruplar 8 dakikalık proje sunumu yapar; akran değerlendirme formu doldurulur.",
  questions=["Bir yıl önce bu dersin başındaki sizinle bugün aranızdaki en büyük fark ne?"],
  summary="Yılı proje sunumlarıyla tamamladık ve “kod yazabilen, veriyle düşünebilen hekim” yolculuğunun sonraki adımlarını tartıştık.",
  before="Proje defterinizi ve sunumunuzu son kez gözden geçirin."),
]

assert [w["n"] for w in WEEKS] == list(range(1, 29)), "28 hafta olmalı"


def yaml_list(items, indent=2):
    pad = " " * indent
    return "\n".join(f'{pad}- {json.dumps(i, ensure_ascii=False)}' for i in items)


def render(w):
    m = module_of(w["n"])
    sem = 1 if w["n"] <= 14 else 2
    fm = [
        "---",
        f'week: {w["n"]}',
        f'title: {json.dumps(w["title"], ensure_ascii=False)}',
        f'topic: {json.dumps(w["topic"], ensure_ascii=False)}',
        f'description: {json.dumps(w["desc"], ensure_ascii=False)}',
        f'module: {m["id"]}',
        f'semester: {sem}',
        f'exam: {"true" if w.get("exam") else "false"}',
        "status: taslak",
        "changeNote: \"\"",
        "tags:",
        yaml_list(w["tags"]),
        "objectives:",
        yaml_list(w["objectives"]),
        "tools:",
        yaml_list(w["tools"]),
        "---",
    ]
    body = []
    if w.get("before"):
        body += ["## Derse Başlamadan Önce", "", w["before"], ""]
    body += ["## Ders Notları", "",
             f"> [!not] Bu bölüm ders notlarının genişletileceği alandır. Haftanın özgün konu başlığı: **{w['topic']}**",
             "", "Ders notları ilerleyen haftalarda buraya eklenecektir.", ""]
    body += ["## Temel Kavramlar", ""]
    for term, d in w["concepts"]:
        body.append(f"- **{term}** — {d}")
    body.append("")
    body += ["## Tıptan Örnekler", ""] + [f"- {e}" for e in w["examples"]] + [""]
    body += ["## Uygulama / Etkinlik", "", w["activity"], ""]
    body += ["## Tartışma Soruları", ""] + [f"{i+1}. {q}" for i, q in enumerate(w["questions"])] + [""]
    body += ["## Haftanın Özeti", "", w["summary"], ""]
    return "\n".join(fm) + "\n\n" + "\n".join(body)


def main():
    force = "--force" in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    written = skipped = 0
    for w in WEEKS:
        path = OUT / f"hafta-{w['n']:02d}.md"
        if path.exists() and not force:
            skipped += 1
            continue
        path.write_text(render(w), encoding="utf-8")
        written += 1
    print(f"Yazıldı: {written}, atlandı (mevcut): {skipped} → {OUT}")


if __name__ == "__main__":
    main()
